### ISSUE TITLE
token

### ISSUE THREAD

**Issue by itzmxrk** [gtagamermods/Djs-Moderation-Bot#6]
I'm not sure if this is just me being stupid, but I can't seem to find the token file in repl.it

**Comment by DevAwpL** [comment]
Its there in environment secrets, on mobile go to commands > secrets > token > paste bot token in value.
On desktop, click on lock icon on the left and do the same. 
If you need further support, join the discord support server.

**Comment by TheReal-iiMark575** [comment]
Oh ye, thanks very much!

**Comment by TheReal-iiMark575** [comment]
Hello again, @DevAwpL 

1) I have the token in, but it still shows that it isn't there, and 2) where can i find the discord server?

Thanks, Mark.

**Comment by DevAwpL** [comment]
> Hello again, @DevAwpL
> 
> 1. I have the token in, but it still shows that it isn't there, and 2) where can i find the discord server?
> 
> Thanks, Mark.

Have you filled that amethyst api or something in config file? If not, it will show missing token error.
And you can join the support server @https://discord.gg/dchelpers

**Comment by itzmxrk** [comment]
No, I haven't. What do I insert there as I am kinda new to coding stuff etc.

**Comment by DevAwpL** [comment]
> No, I haven't. What do I insert there as I am kinda new to coding stuff etc.

You need to go to their website, sign up and get the token from there. It was all mentioned in the tutorial youtube video.
Also, please join the support server and open a ticket there, as it would be more convenient to help.

**Comment by itzmxrk** [comment]
Thanks, I've got it working :D
